[package]
name = "speartacus"
version = "0.1.0"
authors = ["Zakor Gyula <gyula.zakor@h-lab.eu>"]
edition = "2018"

[dependencies]
piston = "0.39.0"
piston_window = "0.85.0"
image = "0.20.1"
rand = "0.6.0"
lazy_static = "1.2.0"
